### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by adityam** [jgm/yst#53]
I am using Arch Linux with GHC 8.10.1. Running `cabal install yst` fails with:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: yst-0.7.1 (user goal)
[__1] trying: time-1.9.3/installed-1.9.3 (dependency of yst)
[__2] trying: deepseq-1.4.4.0/installed-1.4.4.0 (dependency of time)
[__3] trying: array-0.5.4.0/installed-0.5.4.0 (dependency of deepseq)
[__4] trying: parsec-3.1.14.0/installed-3.1.14.0 (dependency of yst)
[__5] next goal: pandoc (dependency of yst)
[__5] rejecting: pandoc-2.9.2.1 (conflict: yst => pandoc>=2.8 && <2.9)
[__5] skipping: pandoc-2.9.2, pandoc-2.9.1.1, pandoc-2.9.1, pandoc-2.9 (has
the same characteristics that caused the previous version to fail: excluded by
constraint '>=2.8 && <2.9' from 'yst')
[__5] trying: pandoc-2.8.1
[__6] trying: zlib-0.6.2.1/installed-IaKBReZRhRdBDsfrN4q94r (dependency of
pandoc)
[__7] next goal: haddock-library (dependency of pandoc)
[__7] rejecting: haddock-library-1.9.0 (conflict: pandoc =>
haddock-library>=1.8 && <1.9)
[__7] rejecting: haddock-library-1.8.0 (conflict: time =>
base==4.14.0.0/installed-4.14.0.0, haddock-library => base>=4.7 && <4.14)
[__7] rejecting: haddock-library-1.7.0 (conflict: pandoc =>
haddock-library>=1.8 && <1.9)
[__7] skipping: haddock-library-1.6.0, haddock-library-1.5.0.1,
haddock-library-1.4.5, haddock-library-1.4.4, haddock-library-1.4.3,
haddock-library-1.4.2, haddock-library-1.4.1, haddock-library-1.2.1,
haddock-library-1.2.0, haddock-library-1.1.1, haddock-library-1.1.0,
haddock-library-1.0.1, haddock-library-1.0.0, haddock-library-1.6.1 (has the
same characteristics that caused the previous version to fail: excluded by
constraint '>=1.8 && <1.9' from 'pandoc')
[__7] fail (backjumping, conflict set: haddock-library, pandoc, time)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, pandoc, haddock-library,
HStringTemplate, time, yst, deepseq, array, pandoc:setup.Cabal, zlib, parsec
Try running with --minimize-conflict-set to improve the error message
```
Running with `--minimize-conflict-set` gives
```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: yst-0.7.1 (user goal)
[__1] next goal: pandoc (dependency of yst)
[__1] rejecting: pandoc-2.9.2.1 (conflict: yst => pandoc>=2.8 && <2.9)
[__1] skipping: pandoc-2.9.2, pandoc-2.9.1.1, pandoc-2.9.1, pandoc-2.9 (has
the same characteristics that caused the previous version to fail: excluded by
constraint '>=2.8 && <2.9' from 'yst')
[__1] trying: pandoc-2.8.1
[__2] next goal: haddock-library (dependency of pandoc)
[__2] rejecting: haddock-library-1.9.0 (conflict: pandoc =>
haddock-library>=1.8 && <1.9)
[__2] trying: haddock-library-1.8.0
[__3] next goal: base (dependency of yst)
[__3] rejecting: base-4.14.0.0/installed-4.14.0.0 (conflict: haddock-library
=> base>=4.7 && <4.14)
[__3] skipping: base-4.14.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=4.7 && <4.14' from
'haddock-library')
[__3] rejecting: base-4.13.0.0, base-4.12.0.0, base-4.11.1.0, base-4.11.0.0,
base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0,
base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0,
base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1,
base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1
(constraint from non-upgradeable package requires installed instance)
[__3] fail (backjumping, conflict set: base, haddock-library, yst)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: pandoc, pandoc:setup.Cabal, yst, base,
haddock-library
```

**Comment by jgm** [comment]
Released version of pandoc doesn't build with ghc 8.10.
That is fixed in the dev version, so when pandoc is next released yst should work too.

**Comment by adityam** [comment]
> Released version of pandoc doesn't build with ghc 8.10.
> That is fixed in the dev version, so when pandoc is next released yst should work too.

Thanks!

**Comment by lesmana** [comment]
any ETA on next release of pandoc?

also question: would this constraint not force yst to still use the old pandoc?

```
[__5] rejecting: pandoc-2.9.2.1 (conflict: yst => pandoc>=2.8 && <2.9)
```

please excuse my ignorance. i am by far no haskell expert.

**Comment by lesmana** [comment]
for arch linux users that have pandoc installed via pacman and try to install yst via cabal the error message will look something like this:

```
Failed to build QuickCheck-2.13.2.
Build log (
/home/lesmana/.cabal/logs/ghc-8.10.1/QuickCheck-2.13.2-bf645fbe2c8ca47ccc44fa3700482e25b98a8b48cbfdcdd9507e0a73088bb398.log
):
Configuring library for QuickCheck-2.13.2..
Preprocessing library for QuickCheck-2.13.2..
Building library for QuickCheck-2.13.2..
[ 1 of 16] Compiling Test.QuickCheck.Exception ( Test/QuickCheck/Exception.hs, dist/build/Test/QuickCheck/Exception.o, dist/build/Test/QuickCheck/Exception.dyn_o )

Test/QuickCheck/Exception.hs:8:8: error:
    Could not find module ‘Prelude’
    There are files missing in the ‘base-4.14.0.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
8 | module Test.QuickCheck.Exception where
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^

Test/QuickCheck/Exception.hs:16:1: error:
    Could not find module ‘Control.Exception’
    There are files missing in the ‘base-4.14.0.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
16 | import qualified Control.Exception as E
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

and

```
cabal: Failed to build QuickCheck-2.13.2 (which is required by exe:yst from
yst-0.7.1). See the build log above for details.
Failed to build aeson-1.4.7.1 (which is required by exe:yst from yst-0.7.1).
See the build log above for details.
Failed to build base64-bytestring-1.0.0.3 (which is required by exe:yst from
yst-0.7.1). See the build log above for details.
```

hopefully this will help people to find this bug and verify that their problem is this bug

**Comment by jgm** [comment]
No ETA but I'll try to do it in the next couple weeks
